frontend/src/router.ts
frontend/src/routes/ErrorNotFound.vue

We have no specification of error handling, yet.
But while developing it's annoying to not be told if a route does not (yet) exist.

Show ErrorNotFound on unknown routes

---

.github/workflows/frontend-build-image-and-scan.yml
.github/workflows/frontend-push-image-to-registry.yml
.github/workflows/pipeline.yml

This failed on main, cf. https://github.com/digitalservicebund/ris-adm-vwv/commit/f383ccbed608743d1912bd31ac0d26d09c4d92ba

Workflow: Pass image ref as input

---

frontend/src/routes/documentUnit/[documentNumber]/RubrikenPage.vue

Use "Zitierdatum" as aria label

---

frontend/src/domain/documentUnit.spec.ts
frontend/src/domain/documentUnit.ts
frontend/src/main.ts
frontend/src/routes/documentUnit/[documentNumber].vue
frontend/src/routes/documentUnit/new.vue
frontend/src/services/documentUnitService.spec.ts
frontend/src/services/documentUnitService.ts
frontend/src/stores/documentUnitStore.spec.ts
frontend/src/stores/documentUnitStore.ts

Create Pinia Store for Documentation Unit

---

frontend/src/domain/documentUnit.spec.ts
frontend/src/domain/documentUnit.ts
frontend/src/routes/documentUnit/[documentNumber]/FundstellenPage.vue
frontend/src/services/documentUnitService.ts
frontend/src/stores/documentUnitStore.spec.ts

Add references in pinia store

---

.github/workflows/frontend-checks.yml
frontend/e2e/RubrikenPage/Langueberschrift.spec.ts
frontend/src/domain/documentUnit.ts
frontend/src/routes/documentUnit/[documentNumber]/RubrikenPage.vue

Persist Langüberschrift

---

frontend/e2e/RubrikenPage/Formaldaten.spec.ts
frontend/src/domain/documentUnit.ts
frontend/src/routes/documentUnit/[documentNumber]/RubrikenPage.vue

Move Zitierdatum tests to non-mocked section

Expect Zitierdatum to persist a reload

---

.github/workflows/combine-e2e-reports.yml
.github/workflows/frontend-checks.yml
.github/workflows/pipeline.yml

Make non-dependency for deployment.

Split off e2e-HTML generation, make non-blocking for deployment

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/field-of-law/FieldsOfLaw.spec.ts
frontend/vitest.config.ts

A previous merge to master resulted in this sonar failure: https://sonarcloud.io/component_measures?metric=new_coverage&selected=ris-adm-vwv-frontend%3Asrc%2Fcomponents&id=ris-adm-vwv-frontend

Istanbul-test-coverage

---

frontend/e2e/RubrikenPage/Schlagwoerter.spec.ts
frontend/package.json
frontend/src/components/KeyWords.spec.ts
frontend/src/components/input/listinput/ListInput.vue
frontend/src/components/input/listinput/ListInputDisplay.vue

Adds a button to enter the edit mode instead of a empty textarea.

RISDEV-7263: Adjust keywords picker UX

---

backend/docker-initialization/create_tables.sql
frontend/e2e/RubrikenPage/Formaldaten.spec.ts
frontend/e2e/RubrikenPage/Schlagwoerter.spec.ts
frontend/src/components/normgeber/NormgeberInput.spec.ts
frontend/src/components/normgeber/NormgeberInput.vue
frontend/src/components/normgeber/NormgeberList.spec.ts
frontend/src/components/normgeber/NormgeberList.vue
frontend/src/components/normgeber/NormgeberListItem.spec.ts
frontend/src/components/normgeber/NormgeberListItem.vue
frontend/src/composables/useEditableList.spec.ts
frontend/src/composables/useEditableList.ts
frontend/src/domain/normgeber.ts
frontend/src/services/comboboxItemService.ts

Add logic to show regions for legal entities as readonly

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnit.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/XmlReader.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/XmlWriter.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/ldml/JaxbHtml.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/XmlReaderTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/XmlWriterTest.java

[RISDEV-7631](https://digitalservicebund.atlassian.net/browse/RISDEV-7631)
Providing a framework for converting XML into Java Business Model (still no section transformed).
[RISDEV-7631]: https://digitalservicebund.atlassian.net/browse/RISDEV-7631?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-7631 Add converter for xml

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/ldml/RisMetadata.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ExpirationDateTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java

https://digitalservicebund.atlassian.net/browse/RISDEV-7759

Return ausserkrafttretedatum

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/KeywordsTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java

https://digitalservicebund.atlassian.net/browse/RISDEV-7756

Read-schlagworte-from-xml-risdev-7756

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/DocumentTypeTransformer.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/DocumentTypeZusatzTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java

[RISDEV-7763](https://digitalservicebund.atlassian.net/browse/RISDEV-7763)
[RISDEV-7763]: https://digitalservicebund.atlassian.net/browse/RISDEV-7763?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Transform document type: abbreviation and name

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ActiveCitationsTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ActiveCitationsTransformerTest.java
backend/src/test/resources/ldml-example.akn.xml

[RISDEV-7764](https://digitalservicebund.atlassian.net/browse/RISDEV-7764)
Add XML transformation of active citations into JSON.
[RISDEV-7764]: https://digitalservicebund.atlassian.net/browse/RISDEV-7764?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-7764 Add active citations transformer

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ActiveReferencesTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ActiveReferencesTransformerTest.java

[RISDEV-7765](https://digitalservicebund.atlassian.net/browse/RISDEV-7765)
Convert active references from XML/LDML into JSON.
[RISDEV-7765]: https://digitalservicebund.atlassian.net/browse/RISDEV-7765?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-7765 Add active references transformer

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/NormReferencesTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceTest.java
backend/src/test/resources/ldml-example.akn.xml

https://digitalservicebund.atlassian.net/browse/RISDEV-7766

Transform norms ("Normenkette") from XML

---

frontend/e2e/RubrikenPage/Kurzrefereat.spec.ts

https://digitalservicebund.atlassian.net/browse/RISDEV-7666

Add e2e: Expand textarea on "Erweitern"

---

frontend/e2e/RubrikenPage/Kurzrefereat.spec.ts

https://digitalservicebund.atlassian.net/browse/RISDEV-7667

Kurzreferat: e2e for hiding non-printable characters

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/LookupTablesPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/LookupTablesPersistencePort.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/FundstellenTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/LookupTablesPersistenceServiceTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/FundstellenTransformerTest.java

[RISDEV-7848](https://digitalservicebund.atlassian.net/browse/RISDEV-7848)
Transform "Fundstelle" with legal periodical from lookup table.
[RISDEV-7848]: https://digitalservicebund.atlassian.net/browse/RISDEV-7848?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-7848 Transform fundstelle with legal periodical

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/InstitutionRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/LookupTablesPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/RegionRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/LookupTablesPersistencePort.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/business/DocumentationUnitContent.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/business/Normgeber.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/ldml/RisNormgeber.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/NormgeberTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitServiceTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/business/DocumentationUnitContentTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/NormgeberTransformerTest.java
backend/src/test/resources/ldml-example.akn.xml
backend/src/test/resources/ldml-no-kurzreferat.akn.xml
frontend/src/components/normgeber/NormgeberInput.spec.ts
frontend/src/components/normgeber/NormgeberInput.vue
frontend/src/components/normgeber/NormgeberList.spec.ts
frontend/src/components/normgeber/NormgeberList.vue
frontend/src/components/normgeber/NormgeberListItem.spec.ts
frontend/src/domain/documentUnit.ts

[RISDEV-7833](https://digitalservicebund.atlassian.net/browse/RISDEV-7833)
Transform normgeber from XML to JSON.
[RISDEV-7833]: https://digitalservicebund.atlassian.net/browse/RISDEV-7833?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-7833 Transform normgeber from XML

---

frontend/e2e/StartPage.spec.ts
frontend/src/components/document-units/DocumentUnitList.spec.ts
frontend/src/components/document-units/DocumentUnitList.vue
frontend/src/components/document-units/DocumentUnits.vue
frontend/src/domain/documentUnit.ts
frontend/src/domain/fundstelle.ts
frontend/src/services/documentUnitService.ts

https://digitalservicebund.atlassian.net/browse/RISDEV-7787
Data in the backend is still hard-coded.

Frontend to read the list of document units via an API call (RISDEV-7787)

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitIndexRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnit.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitTest.java
backend/src/test/resources/json-example.json
backend/src/test/resources/ldml-example.akn.xml

RISDEV-8063 create indexing method

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/Application.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitEntity.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitIndexJob.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnit.java
backend/src/main/resources/application.yaml
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitEntityTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceServiceIntegrationTest.java

RISDEV-8064 Add indexing job for documentation units

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/Application.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitEntity.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitIndexJob.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnit.java
backend/src/main/resources/application.yaml
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitEntityTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceServiceIntegrationTest.java

Risdev 8078 reindex on update

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitIndexJob.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitRepository.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/transform/ActiveReferencesTransformer.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceServiceIntegrationTest.java
backend/src/test/resources/application-test.yaml

[RISDEV-8119](https://digitalservicebund.atlassian.net/browse/RISDEV-8119)
Execute indexing of documentation units in batches per 500 items.
[RISDEV-8119]: https://digitalservicebund.atlassian.net/browse/RISDEV-8119?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-8119 Refactor indexing job

---

frontend/src/components/document-units/SearchPanel.spec.ts
frontend/src/components/document-units/SearchPanel.vue

Add date validation to search

---

.github/workflows/backend-build-image-and-scan.yml
.github/workflows/backend-checks.yml
.github/workflows/e2e-tests.yml
.github/workflows/unpin-backend-libraries.yml

https://digitalservicebund.atlassian.net/browse/RISDEV-8295
Reduce duplicated steps by merging the build/test/sonar steps in our pipeline.

Merge build/test/sonar in single job

---

.github/workflows/backend-checks.yml
.github/workflows/backend-push-reports-to-ris-reports.yml
.github/workflows/pipeline.yml

https://digitalservicebund.atlassian.net/browse/RISDEV-8288

Publish ADRs (RISDEV-8288)

---

frontend/src/components/document-units/DocumentUnits.spec.ts
frontend/src/components/document-units/DocumentUnits.vue
frontend/src/composables/usePagination.spec.ts
frontend/src/composables/usePagination.ts
frontend/src/utils/dateHelpers.ts

- Remove console logging on error, should be caught in sentry
- Move error toast logic to the calling component

RISDEV-8473: Remove logging in the console

---

backend/build.gradle.kts

https://github.com/digitalservicebund/ris-adm-vwv/security/code-scanning/35
https://github.com/digitalservicebund/ris-adm-vwv/security/code-scanning/34

Pinning two libs due to CVE-2025-48924 and CVE-2025-53864

---

frontend/src/components/NavbarTop.spec.ts
frontend/src/services/auth.spec.ts
frontend/src/services/auth.ts

Remove unneeded auth.ts code

---

.lefthook/pre-commit/trivy-secrets.sh
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/api/DocumentationUnitController.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitPersistencePort.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitPort.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitService.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterService.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/api/DocumentationUnitControllerTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/persistence/DocumentationUnitPersistenceServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/DocumentationUnitServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/LdmlConverterServiceIntegrationTest.java
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/application/converter/business/TestDocumentationUnitContent.java
backend/src/test/resources/ldml-example.akn.xml

[RISDEV-8874](https://digitalservicebund.atlassian.net/browse/RISDEV-8874)
Provide a base in `LDMLConverterService` for creating LDML.
[RISDEV-8874]: https://digitalservicebund.atlassian.net/browse/RISDEV-8874?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

RISDEV-8874 Add LDML converter base

---

.github/workflows/e2e-tests.yml
frontend/playwright.config.ts

https://digitalservicebund.atlassian.net/browse/RISDEV-8849

Update e2e pipeline to include login tests

---

doc/adr/0010-single-app-for-administrative-directives-and-literature.md
doc/adr/0010-single-app-for-vwv-and-literature.md

https://digitalservicebund.atlassian.net/browse/RISDEV-8924

ADR: Single app for multiple document types and workflows (RISDEV-8924)

---

frontend/e2e/StartPage.spec.ts
frontend/src/components/NavbarTop.spec.ts
frontend/src/components/NavbarTop.vue

Add main nav Suche link

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/publishing/S3PublishAdapter.java
backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/config/PublisherConfig.java
backend/src/main/resources/application-staging.yaml
backend/src/main/resources/application.yaml
backend/src/test/java/de/bund/digitalservice/ris/adm_vwv/adapter/publishing/S3PublishAdapterIntegrationTest.java
backend/src/test/resources/application-test.yaml

Changelog publishing

---

backend/src/main/java/de/bund/digitalservice/ris/adm_vwv/adapter/publishing/S3PublishAdapter.java

Propagate publish exception

---

backend/build.gradle.kts

Exclusion caused a compilation error, cf. https://github.com/digitalservicebund/ris-adm-vwv/actions/runs/17366816402/job/49294991793

Use apache.commons-lang3 without an exclusion

---

backend/build.gradle.kts

Pin netty-codec, exclude from awssdk:s3
